### ISSUE TITLE
Create json file to read movie names

### ISSUE THREAD

**Issue by harikesh409** [harikesh409/Entertainment-Center#1]
https://github.com/harikesh409/Entertainment-Center/blob/6f9713ae124dbc5a6033dfb911ec0f878fd3fd3e/entertainment_center.py#L8

Instead of hardcoding movie names in an array read a JSON file where a list of movie names are present.

**Comment by ehoward119** [comment]
I would like to take up this issue. Do you want me to create a JSON file to read from or keep it general and have one be passed in?

**Comment by Pandiurex** [comment]
Can i help u?

**Comment by harikesh409** [comment]
> I would like to take up this issue. Do you want me to create a JSON file to read from or keep it general and have one be passed in?

You need to read the data from the JSON file. This data should be used while generating the HTML page.

**Comment by abhinav-bhardwaj** [comment]
are you going to create the JSON file from scraping some website or you're going to hardcode?

**Comment by harikesh409** [comment]
> are you going to create the JSON file from scraping some website or you're going to hardcode?

For this issue we leave as hardcoding I have opened another issue to scrape data refer that #7
