### ISSUE TITLE
Default image

### ISSUE THREAD

**Issue by harikesh409** [harikesh409/Entertainment-Center#3]
Add a default image of your choice if the image is not present in API.

**Comment by DhawalKhapre** [comment]
Can I help?
This is my first-time on open-source

**Comment by harikesh409** [comment]
> Can I help?
> This is my first-time on open-source

Sure you can give it a shot. All the best.

**Comment by DhawalKhapre** [comment]
I tried to fix the issue in the python files.
I may be wrong here......but the urls for the imgs have been hardcoded in the html file. So the only fix I have now is to see which images are absent and give the url of the stock image in that movie's block in html file

**Comment by harikesh409** [comment]
> I tried to fix the issue in the python files.
> I may be wrong here......but the urls for the imgs have been hardcoded in the html file. So the only fix I have now is to see which images are absent and give the url of the stock image in that movie's block in html file

That is just a sample html file the main is python only, raise a pr with your code.
